#!/bin/sh -e

usage () {
  printf "Usage: %s: [-s token] [-e token] [file]\n" "$0"
  exit 2
}

stag="<%"
etag="%>"
while getopts s:e: name
do
  case $name in
    s)  stag="$OPTARG";;
    e)  etag="$OPTARG";;
    ?)  usage;;
  esac
done
shift $(($OPTIND - 1))

case $# in
  0)  file=$(cat);;
  1)
    if [ ! -f "$1" ]; then
      printf "File not found: %s\n" "$1"
      exit 2
    fi
    file=$(cat "$1")
    ;;
  ?)  usage;;
esac

front=$(echo "${file}" | awk '/^---$/ { frontmatter = NR; next } frontmatter == 1 { print }')
back=$(echo -n "${file}" | awk '/^---$/ { frontmatter = NR; next } frontmatter != 1 { print }')

script=$(echo -n "${etag}${back}${stag}" | sed \
  -e "s|${stag}=|${stag}printf \"%s\" |g" \
  -e "s|${stag}|\n${stag}\n)\"\n|g" \
  -e "s|${etag}|\nprintf \"%s\" \"\$(cat<<'${stag}'\n|g" \
  )

eval "$front $script"

