#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $(basename $0) file"
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "File not found: $1"
  exit 1
fi

stag="{{"
etag="}}"

{ echo -n "#!/bin/sh -e"; echo -n "$etag"; cat "$1"; echo -n "$stag"; } | sed \
  -e "s|${stag}=|${stag}echo -n |g" \
  -e "s|${stag}|\n${stag}\n)\"\n|g" \
  -e "s|${etag}|\necho -n \"\$(cat<<'${stag}'\n|g"
